/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI2
 */
public class tao_hd extends javax.swing.JFrame {

    /**
     * Creates new form Ban_hang
     */
    public tao_hd() {
        initComponents();
    }
    
    /**
     *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_tracu = new javax.swing.JFrame();
        bg_tracuuhd = new javax.swing.JPanel();
        sidepane9 = new javax.swing.JPanel();
        bg_trangchu9 = new javax.swing.JPanel();
        text_trangchu9 = new javax.swing.JLabel();
        icon_trangchu9 = new javax.swing.JLabel();
        bg_banhang2 = new javax.swing.JPanel();
        icon_banhang2 = new javax.swing.JLabel();
        button_banhang2 = new javax.swing.JButton();
        bg_thucdon2 = new javax.swing.JPanel();
        icon_thucdon2 = new javax.swing.JLabel();
        button_thucdon2 = new javax.swing.JButton();
        bg_address2 = new javax.swing.JPanel();
        text_cafeomely4 = new javax.swing.JLabel();
        icon_cafe4 = new javax.swing.JLabel();
        bg_thoat2 = new javax.swing.JPanel();
        button_thoat2 = new javax.swing.JButton();
        bg_chuquan2 = new javax.swing.JPanel();
        bg_cafeomely2 = new javax.swing.JPanel();
        text_cafeomely5 = new javax.swing.JLabel();
        icon_cafe5 = new javax.swing.JLabel();
        bg_cafe_cake2 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        bg7 = new javax.swing.JPanel();
        bg_thoat = new javax.swing.JPanel();
        bg_trangchu7 = new javax.swing.JPanel();
        text_trangchu7 = new javax.swing.JLabel();
        icon_trangchu7 = new javax.swing.JLabel();
        button_thoat = new javax.swing.JButton();
        bg_home_banhang = new javax.swing.JPanel();
        them_hd = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jText_TenMon = new javax.swing.JTextField();
        jText_MaKH = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jSpinner_SoLuong = new javax.swing.JSpinner();
        jText_TongCong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jText_GiamGia = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jText_ThanhToan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton_them_luachon = new javax.swing.JButton();
        jComboBox_MaBan = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_CTHD = new javax.swing.JTable();
        jTextField9 = new javax.swing.JTextField();
        jButton_bochon = new javax.swing.JButton();
        jButton_Thanhtoan = new javax.swing.JButton();
        themhd = new javax.swing.JPanel();
        icon_themhd = new javax.swing.JLabel();
        button_themhd = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bg_address = new javax.swing.JPanel();
        text_cafeomely1 = new javax.swing.JLabel();
        icon_cafe1 = new javax.swing.JLabel();
        icon_cafe = new javax.swing.JLabel();
        text_cafeomely = new javax.swing.JLabel();

        bg_tracuuhd.setBackground(new java.awt.Color(255, 255, 255));
        bg_tracuuhd.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bg_tracuuhd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane9.setBackground(new java.awt.Color(54, 33, 89));
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_trangchu9.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu9.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu9.setText("Bán Hàng");

        icon_trangchu9.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu9.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_online_store_32px.png"))); // NOI18N
        icon_trangchu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu9.setOpaque(true);

        javax.swing.GroupLayout bg_trangchu9Layout = new javax.swing.GroupLayout(bg_trangchu9);
        bg_trangchu9.setLayout(bg_trangchu9Layout);
        bg_trangchu9Layout.setHorizontalGroup(
            bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_trangchu9Layout.createSequentialGroup()
                .addComponent(icon_trangchu9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
            .addGroup(bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_trangchu9Layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(text_trangchu9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        bg_trangchu9Layout.setVerticalGroup(
            bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_trangchu9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(text_trangchu9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        sidepane9.add(bg_trangchu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        bg_banhang2.setBackground(new java.awt.Color(85, 65, 118));

        icon_banhang2.setBackground(new java.awt.Color(54, 33, 89));
        icon_banhang2.setForeground(new java.awt.Color(255, 255, 255));
        icon_banhang2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_banhang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_shop_26px.png"))); // NOI18N
        icon_banhang2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_banhang2.setOpaque(true);

        button_banhang2.setBackground(new java.awt.Color(54, 33, 89));
        button_banhang2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_banhang2.setForeground(new java.awt.Color(255, 255, 255));
        button_banhang2.setText("Thêm hóa đơn mới");
        button_banhang2.setOpaque(false);
        button_banhang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_banhang2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_banhang2Layout = new javax.swing.GroupLayout(bg_banhang2);
        bg_banhang2.setLayout(bg_banhang2Layout);
        bg_banhang2Layout.setHorizontalGroup(
            bg_banhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_banhang2Layout.createSequentialGroup()
                .addComponent(icon_banhang2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_banhang2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_banhang2Layout.setVerticalGroup(
            bg_banhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_banhang2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_banhang2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane9.add(bg_banhang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 310, 40));

        bg_thucdon2.setBackground(new java.awt.Color(85, 65, 118));

        icon_thucdon2.setBackground(new java.awt.Color(54, 33, 89));
        icon_thucdon2.setForeground(new java.awt.Color(255, 255, 255));
        icon_thucdon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_thucdon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_cutlery_26px.png"))); // NOI18N
        icon_thucdon2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_thucdon2.setOpaque(true);

        button_thucdon2.setBackground(new java.awt.Color(54, 33, 89));
        button_thucdon2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thucdon2.setForeground(new java.awt.Color(255, 255, 255));
        button_thucdon2.setText("Tra cứu hóa đơn");
        button_thucdon2.setActionCommand("Thực dơn");
        button_thucdon2.setOpaque(false);
        button_thucdon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thucdon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thucdon2Layout = new javax.swing.GroupLayout(bg_thucdon2);
        bg_thucdon2.setLayout(bg_thucdon2Layout);
        bg_thucdon2Layout.setHorizontalGroup(
            bg_thucdon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_thucdon2Layout.createSequentialGroup()
                .addComponent(icon_thucdon2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_thucdon2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bg_thucdon2Layout.setVerticalGroup(
            bg_thucdon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_thucdon2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_thucdon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane9.add(bg_thucdon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, 40));

        bg_address2.setBackground(new java.awt.Color(85, 65, 118));
        bg_address2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_cafeomely4.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely4.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely4.setText("OMELY QUÁN");
        bg_address2.add(text_cafeomely4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 0, 235, 56));

        icon_cafe4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N
        bg_address2.add(icon_cafe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        sidepane9.add(bg_address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 310, 50));

        bg_tracuuhd.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 620));

        bg_thoat2.setBackground(new java.awt.Color(85, 65, 118));

        button_thoat2.setBackground(new java.awt.Color(255, 51, 0));
        button_thoat2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat2.setForeground(new java.awt.Color(255, 255, 255));
        button_thoat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_back_32px.png"))); // NOI18N
        button_thoat2.setText("Thoát");
        button_thoat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        button_thoat2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout bg_thoat2Layout = new javax.swing.GroupLayout(bg_thoat2);
        bg_thoat2.setLayout(bg_thoat2Layout);
        bg_thoat2Layout.setHorizontalGroup(
            bg_thoat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoat2Layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(button_thoat2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_thoat2Layout.setVerticalGroup(
            bg_thoat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_thoat2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_tracuuhd.add(bg_thoat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 690, 60));

        bg_chuquan2.setBackground(new java.awt.Color(54, 33, 89));
        bg_chuquan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_cafeomely2.setBackground(new java.awt.Color(85, 65, 118));

        text_cafeomely5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_cafeomely5.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely5.setText("Đ/C: Thị trấn Phú Phong, huyện Tây Sơn, tỉnh Bình Định.");

        icon_cafe5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafeomely2Layout = new javax.swing.GroupLayout(bg_cafeomely2);
        bg_cafeomely2.setLayout(bg_cafeomely2Layout);
        bg_cafeomely2Layout.setHorizontalGroup(
            bg_cafeomely2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_cafeomely2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(icon_cafe5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_cafeomely5, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_cafeomely2Layout.setVerticalGroup(
            bg_cafeomely2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_cafe5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(text_cafeomely5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg_chuquan2.add(bg_cafeomely2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 690, 50));

        bg_cafe_cake2.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout bg_cafe_cake2Layout = new javax.swing.GroupLayout(bg_cafe_cake2);
        bg_cafe_cake2.setLayout(bg_cafe_cake2Layout);
        bg_cafe_cake2Layout.setHorizontalGroup(
            bg_cafe_cake2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        bg_cafe_cake2Layout.setVerticalGroup(
            bg_cafe_cake2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        bg_chuquan2.add(bg_cafe_cake2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 470));

        bg_tracuuhd.add(bg_chuquan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 690, 560));

        javax.swing.GroupLayout home_tracuLayout = new javax.swing.GroupLayout(home_tracu.getContentPane());
        home_tracu.getContentPane().setLayout(home_tracuLayout);
        home_tracuLayout.setHorizontalGroup(
            home_tracuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_tracuuhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        home_tracuLayout.setVerticalGroup(
            home_tracuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_tracuuhd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg7.setBackground(new java.awt.Color(255, 255, 255));
        bg7.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bg7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_thoat.setBackground(new java.awt.Color(85, 65, 118));

        bg_trangchu7.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu7.setText("Bán hàng");

        icon_trangchu7.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_online_store_32px.png"))); // NOI18N
        icon_trangchu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu7.setOpaque(true);

        javax.swing.GroupLayout bg_trangchu7Layout = new javax.swing.GroupLayout(bg_trangchu7);
        bg_trangchu7.setLayout(bg_trangchu7Layout);
        bg_trangchu7Layout.setHorizontalGroup(
            bg_trangchu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_trangchu7Layout.createSequentialGroup()
                .addComponent(icon_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        bg_trangchu7Layout.setVerticalGroup(
            bg_trangchu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(icon_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        button_thoat.setBackground(new java.awt.Color(255, 255, 255));
        button_thoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat.setForeground(new java.awt.Color(204, 51, 0));
        button_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_back_arrow_30px.png"))); // NOI18N
        button_thoat.setText("Thoát");
        button_thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thoatLayout = new javax.swing.GroupLayout(bg_thoat);
        bg_thoat.setLayout(bg_thoatLayout);
        bg_thoatLayout.setHorizontalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addComponent(bg_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 581, Short.MAX_VALUE)
                .addComponent(button_thoat)
                .addContainerGap())
        );
        bg_thoatLayout.setVerticalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_thoat)
                .addContainerGap())
        );

        bg7.add(bg_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        bg_home_banhang.setBackground(new java.awt.Color(54, 33, 89));
        bg_home_banhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        them_hd.setBackground(new java.awt.Color(54, 33, 89));
        them_hd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg_home_banhang.add(them_hd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jTextField5.setBackground(new java.awt.Color(54, 33, 89));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Số lượng");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 90, 30));

        jText_TenMon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jText_TenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_TenMonActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jText_TenMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 240, 30));

        jText_MaKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bg_home_banhang.add(jText_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 240, 30));

        jTextField8.setBackground(new java.awt.Color(54, 33, 89));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Tên món");
        jTextField8.setBorder(null);
        bg_home_banhang.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));
        bg_home_banhang.add(jSpinner_SoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 80, 30));

        jText_TongCong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bg_home_banhang.add(jText_TongCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 240, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("%");
        bg_home_banhang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 50, 30));

        jTextField12.setBackground(new java.awt.Color(54, 33, 89));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("%Giảm giá:");
        jTextField12.setBorder(null);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 120, 30));

        jText_GiamGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bg_home_banhang.add(jText_GiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 50, 30));

        jTextField14.setBackground(new java.awt.Color(54, 33, 89));
        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("Thanh toán:");
        jTextField14.setBorder(null);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 120, 30));

        jText_ThanhToan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bg_home_banhang.add(jText_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VND");
        bg_home_banhang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 50, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mã khách hàng");
        bg_home_banhang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 30));

        jTextField16.setBackground(new java.awt.Color(54, 33, 89));
        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("Tổng cộng:");
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 120, 30));

        jButton_them_luachon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_them_luachon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_add_new_16px.png"))); // NOI18N
        jButton_them_luachon.setText("Thêm");
        jButton_them_luachon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 2));
        jButton_them_luachon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_them_luachonActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jButton_them_luachon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 100, 30));

        jComboBox_MaBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MS21", "MS11", "MS23", "MS46", "MS38", " " }));
        bg_home_banhang.add(jComboBox_MaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 80, 30));

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Mã bàn", "Tên món", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(jTable_CTHD);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 900, 160));

        jTextField9.setBackground(new java.awt.Color(85, 65, 118));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Thông tin chi tiết hóa đơn");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 250, 30));

        jButton_bochon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_bochon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/delete.png"))); // NOI18N
        jButton_bochon.setText("Bỏ chọn");
        jButton_bochon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 2));
        jButton_bochon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bochonActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_bochon, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 100, 30));

        jButton_Thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Thanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_cash_in_hand_40px.png"))); // NOI18N
        jButton_Thanhtoan.setText("Thanh toán");
        jButton_Thanhtoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        jButton_Thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThanhtoanActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Thanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 140, 40));

        themhd.setBackground(new java.awt.Color(204, 255, 204));

        icon_themhd.setBackground(new java.awt.Color(54, 33, 89));
        icon_themhd.setForeground(new java.awt.Color(255, 255, 255));
        icon_themhd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_themhd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/banhang/icons8_add_new_26px.png"))); // NOI18N
        icon_themhd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_themhd.setOpaque(true);

        button_themhd.setBackground(new java.awt.Color(54, 33, 89));
        button_themhd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_themhd.setForeground(new java.awt.Color(255, 255, 255));
        button_themhd.setText("Thêm hóa đơn mới");
        button_themhd.setOpaque(false);
        button_themhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_themhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themhdLayout = new javax.swing.GroupLayout(themhd);
        themhd.setLayout(themhdLayout);
        themhdLayout.setHorizontalGroup(
            themhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themhdLayout.createSequentialGroup()
                .addComponent(icon_themhd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_themhd)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        themhdLayout.setVerticalGroup(
            themhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_themhd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_themhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(themhd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 210, -1));

        bg_home_banhang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 960, 270));

        jTextField10.setBackground(new java.awt.Color(54, 33, 89));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Mã bàn");
        jTextField10.setBorder(null);
        bg_home_banhang.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VND");
        bg_home_banhang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 50, 30));

        bg7.add(bg_home_banhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 510));

        bg_address.setBackground(new java.awt.Color(85, 65, 118));
        bg_address.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_cafeomely1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely1.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely1.setText("OMELY QUÁN ");
        bg_address.add(text_cafeomely1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 280, 56));

        icon_cafe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N
        bg_address.add(icon_cafe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        icon_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N
        bg_address.add(icon_cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 79, 56));

        text_cafeomely.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_cafeomely.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely.setText("Đ/C: Thị trấn Phú Phong, huyện Tây Sơn, tỉnh Bình Định.");
        bg_address.add(text_cafeomely, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 523, 50));

        bg7.add(bg_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1000, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_themhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_themhdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_themhdActionPerformed

    private void button_banhang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_banhang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_banhang2ActionPerformed

    private void button_thucdon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thucdon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_thucdon2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton_ThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThanhtoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ThanhtoanActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jText_TenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_TenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TenMonActionPerformed

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thoatActionPerformed
        // TODO add your handling code here:
        new home_banhang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_thoatActionPerformed

    private void jButton_them_luachonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_them_luachonActionPerformed
        // TODO add your handling code here:
        if((jText_MaKH.getText().equals("")) || (jText_TenMon.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Dữ liệu chưa được nhập đủ! Hãy thử lại!", "Lỗi",JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
            DefaultTableModel model = (DefaultTableModel)jTable_CTHD.getModel();
            Object [] row = new Object[4];
            row[0] = jText_MaKH.getText();
            row[1] = jComboBox_MaBan.getSelectedItem().toString();
            row[2] = jText_TenMon.getText();
            row[3] = jSpinner_SoLuong.getValue();
            model.addRow(row);
        }
    }//GEN-LAST:event_jButton_them_luachonActionPerformed

    private void jButton_bochonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bochonActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel)jTable_CTHD.getModel();
        //Delete Selected Row        
        int getSelectedRowForDeletion = jTable_CTHD.getSelectedRow();
        //Check if their is a row selected
        if (getSelectedRowForDeletion >= 0) {
            model.removeRow(getSelectedRowForDeletion);
            JOptionPane.showMessageDialog(null, "Row Deleted");
        } else {
            JOptionPane.showMessageDialog(null, "Unable To Delete");
        }
    }//GEN-LAST:event_jButton_bochonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tao_hd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg7;
    private javax.swing.JPanel bg_address;
    private javax.swing.JPanel bg_address2;
    private javax.swing.JPanel bg_banhang2;
    private javax.swing.JPanel bg_cafe_cake2;
    private javax.swing.JPanel bg_cafeomely2;
    private javax.swing.JPanel bg_chuquan2;
    private javax.swing.JPanel bg_home_banhang;
    private javax.swing.JPanel bg_thoat;
    private javax.swing.JPanel bg_thoat2;
    private javax.swing.JPanel bg_thucdon2;
    private javax.swing.JPanel bg_tracuuhd;
    private javax.swing.JPanel bg_trangchu7;
    private javax.swing.JPanel bg_trangchu9;
    private javax.swing.JButton button_banhang2;
    private javax.swing.JButton button_themhd;
    private javax.swing.JButton button_thoat;
    private javax.swing.JButton button_thoat2;
    private javax.swing.JButton button_thucdon2;
    private javax.swing.JFrame home_tracu;
    private javax.swing.JLabel icon_banhang2;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_cafe1;
    private javax.swing.JLabel icon_cafe4;
    private javax.swing.JLabel icon_cafe5;
    private javax.swing.JLabel icon_themhd;
    private javax.swing.JLabel icon_thucdon2;
    private javax.swing.JLabel icon_trangchu7;
    private javax.swing.JLabel icon_trangchu9;
    private javax.swing.JButton jButton_Thanhtoan;
    private javax.swing.JButton jButton_bochon;
    private javax.swing.JButton jButton_them_luachon;
    private javax.swing.JComboBox<String> jComboBox_MaBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_SoLuong;
    private javax.swing.JTable jTable_CTHD;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jText_GiamGia;
    private javax.swing.JTextField jText_MaKH;
    private javax.swing.JTextField jText_TenMon;
    private javax.swing.JTextField jText_ThanhToan;
    private javax.swing.JTextField jText_TongCong;
    private javax.swing.JPanel sidepane9;
    private javax.swing.JLabel text_cafeomely;
    private javax.swing.JLabel text_cafeomely1;
    private javax.swing.JLabel text_cafeomely4;
    private javax.swing.JLabel text_cafeomely5;
    private javax.swing.JLabel text_trangchu7;
    private javax.swing.JLabel text_trangchu9;
    private javax.swing.JPanel them_hd;
    private javax.swing.JPanel themhd;
    // End of variables declaration//GEN-END:variables
}
